name: Automated Tests
on: [push]
jobs:
  Contract-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Building on Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'
      - name: npm update
        run: npm install -g npm@7.18.1
      - name: Install dependencies
        run: npm i --no-audit --legacy-peer-deps
      - name: Execute Tests
        run: npm run test:contracts